# Generated by Django 6.0 on 2026-01-12 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_receive_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recruited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruits', to=settings.AUTH_USER_MODEL),
        ),
    ]
