# Generated by Django 6.0 on 2026-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_recruited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('color', models.CharField(default='#FFD700', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='winners', to='users.award'),
        ),
    ]
