# Generated by Django 6.0 on 2026-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_award_user_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_attendance',
            field=models.BooleanField(default=False, help_text='Designates whether this executive can scan/manage student attendance.'),
        ),
    ]
