# Generated by Django 6.0 on 2026-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_can_manage_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manual_bonus_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Admins can use this to manually add or subtract hours from the student's total.", max_digits=6),
        ),
    ]
