# Generated by Django 6.0 on 2026-06-15 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_2fa_enabled_user_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
        migrations.CreateModel(
            name='VolunteerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('40_hours', '40 Hours Milestone'), ('80_hours', '80 Hours Milestone')], max_length=20)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
