# Generated by Django 6.0 on 2026-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_2fa_enabled_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='date_awarded',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
