# Generated by Django 6.0 on 2026-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_award_date_awarded_award_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Gamified learning points earned from LMS quizzes'),
        ),
    ]
