# Generated by Django 6.0 on 2026-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer_status',
            field=models.CharField(blank=True, choices=[('SENIOR', 'Senior (Returning)'), ('NEWCOMER', 'Newcomer (First Time)')], max_length=20, null=True),
        ),
    ]
