# Generated by Django 6.0 on 2026-08-31 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_gender_user_tshirt_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="student_number",
        ),
    ]
