# Generated by Django 6.0 on 2026-09-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_user_student_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="13-digit South African National ID number",
                max_length=13,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="popia_consent",
            field=models.BooleanField(
                default=False,
                help_text="Consent to personal data collection under the POPI Act",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="popia_consent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when POPIA consent was granted",
                null=True,
            ),
        ),
    ]
