# Generated by Django 6.0 on 2026-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_id_number_user_popia_consent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("SA_ID", "South African ID"),
                    ("PASSPORT", "Passport (International)"),
                ],
                default="SA_ID",
                help_text="Identification document type (South African ID or International Passport)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="South African National ID or International Passport number",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
    ]
