# Generated by Django 6.0 on 2026-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_id_type_alter_user_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_camp_eligible",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this student is eligible to receive a Year-End Camp ticket.",
            ),
        ),
    ]
