# Generated by Django 6.0 on 2026-01-07 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('campus', models.CharField(choices=[('APB', 'APB Campus'), ('DFC', 'DFC Campus'), ('APK', 'APK Campus'), ('SWC', 'SWC Campus'), ('ALL', 'All Campuses')], default='ALL', max_length=10)),
                ('description', models.TextField(help_text='Short summary of the event')),
                ('details', models.TextField(help_text='Full detailed explanation')),
                ('total_spots', models.PositiveIntegerField()),
                ('spots_taken', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True, help_text='What to bring, dress code, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
