# Generated by Django 6.0 on 2026-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeractivity',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duration in hours (e.g. 2.5)', max_digits=4, null=True),
        ),
    ]
