# Generated by Django 6.0 on 2026-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_volunteeractivity_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeractivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
    ]
