# Generated by Django 6.0 on 2026-01-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteeractivity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('Set Up', 'Set Up - Preparing for the event'), ('Demonstration', 'Demonstration - Showcase safety tips'), ('Recruitment', 'Recruitment - Convince fellow students to join'), ('General', 'General Helper')], default='General', max_length=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.volunteeractivity')),
            ],
        ),
    ]
