# Generated by Django 6.0 on 2026-01-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitysignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysignup',
            name='hours_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='activitysignup',
            name='sign_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitysignup',
            name='sign_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
