# Generated by Django 6.0 on 2026-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitysignup_hours_earned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysignup',
            name='selected_role',
        ),
        migrations.AddField(
            model_name='activitysignup',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.activityrole'),
        ),
    ]
