# Generated by Django 6.0 on 2026-02-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_activitysignup_selected_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysignup',
            name='sign_in_facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_signins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysignup',
            name='sign_out_facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_signouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
