# Generated by Django 6.0 on 2026-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitysignup_sign_in_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeractivity',
            name='ai_insight',
            field=models.TextField(blank=True, help_text='Cached AI analysis for reporting', null=True),
        ),
    ]
