# Generated by Django 6.0 on 2026-03-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_volunteeractivity_ai_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeractivity',
            name='total_spots',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited spots', null=True),
        ),
    ]
