# Generated by Django 6.0 on 2026-03-07 20:25

import config.gcloud
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_volunteeractivity_total_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeractivity',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.gcloud.GoogleCloudMediaFileStorage(), upload_to=core.models.secure_profile_path),
        ),
    ]
