# Generated by Django 6.0 on 2026-06-09 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerToolkitAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('cv', 'CV Experience Section'), ('linkedin', 'LinkedIn Summary'), ('scholarship', 'Application Statement')], max_length=20)),
                ('generated_content', models.TextField()),
                ('hours_at_generation', models.FloatField(default=0.0)),
                ('events_at_generation', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset_type')},
            },
        ),
    ]
