# Generated by Django 6.0 on 2026-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_excursionticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysignup',
            name='session_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
