# Generated by Django 6.0 on 2026-08-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_activitysignup_session_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionticket',
            name='locked_hours',
            field=models.FloatField(default=0.0, help_text='Hours locked at initial ticket generation'),
        ),
        migrations.CreateModel(
            name='ExcursionLeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-locked_hours', 'created_at'],
            },
        ),
    ]
