# Generated by Django 6.0 on 2026-08-31 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_excursionticket_locked_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. ATTENDANCE_VERIFIED, MANUAL_HOURS_ALLOCATED",
                        max_length=100,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Entity type e.g. ActivitySignup, User, Topic",
                        max_length=100,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID or UUID of the affected entity",
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sanitized contextual metadata without sensitive data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the action, or null if system-generated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_auditl_action_d80c2d_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="core_auditl_target__6c66b3_idx",
                    ),
                ],
            },
        ),
    ]
