# Generated by Django 6.0 on 2026-09-22 14:43

import config.gcloud
import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampLeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked_hours", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camp_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-locked_hours", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fallback_pin", models.CharField(max_length=8, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("confirmed", "Confirmed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "locked_hours",
                    models.FloatField(
                        default=0.0,
                        help_text="Hours locked at camp ticket generation (cutoff 28 Sept 2026)",
                    ),
                ),
                (
                    "lms_modules_summary",
                    models.CharField(
                        default="All Core Modules Completed",
                        help_text="Summary of LMS modules mastered",
                        max_length=255,
                    ),
                ),
                (
                    "drives_attended_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of major volunteer drives attended"
                    ),
                ),
                (
                    "major_drives_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Titles of notable drives attended",
                    ),
                ),
                (
                    "cohort_rank",
                    models.PositiveIntegerField(
                        default=1, help_text="Leaderboard rank among the 78 qualifiers"
                    ),
                ),
                (
                    "honor_title",
                    models.CharField(
                        default="Certified Peer Educator",
                        help_text="Honor title (e.g. Senior Peer Educator)",
                        max_length=100,
                    ),
                ),
                (
                    "dietary_preference",
                    models.CharField(
                        blank=True,
                        help_text="Dietary preference for camp meals",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tshirt_size",
                    models.CharField(
                        blank=True,
                        help_text="Confirmed T-Shirt size",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=config.gcloud.GoogleCloudMediaFileStorage(),
                        upload_to=core.models.secure_qr_path,
                    ),
                ),
                ("is_scanned", models.BooleanField(default=False)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camp_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["cohort_rank", "-locked_hours"],
            },
        ),
    ]
