# Generated by Django 6.0 on 2026-09-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_campleaderboardsnapshot_campticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campticket",
            name="dietary_preference",
        ),
    ]
