# Generated by Django 6.0 on 2026-06-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='media_file',
        ),
    ]
